config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'photo_albums#index'

  resources :photo_albums, only: :index do
    resources :photos, only: [:index, :show]
  end

  get 'downloads/photo_download'

  get 'photo_albums/:photo_album_id/photos/filter/:date', to: 'photos#index', as: 'photos_filter'
  get 'photo_albums/:photo_album_id/dates', to: 'photos#dates'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, PhotoAlbum
    else
      can :manage, Photo
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  extend Enumerize

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  enumerize :role, in: [:photograph, :admin], predicates: true

  belongs_to :photo_album
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include ActiveModel::Validations

  belongs_to :photo_album

  mount_uploaders :files, FileUploader

  validates :date, :photo_album_id, presence: true
  validate :check_files

  def check_files
    if self.files.present?
      res = true
      self.files.map do |file| 
        if file.size >= 15.megabytes
          res = false
          errors.add(:files, "Изображение превышает допустивый лимит в 15мб")
          break
        end
      end
      return res
    else
      errors.add(:files, "Добавьте изображения")
      false
    end
  end
end

app/models/photo_album.rb
class PhotoAlbum < ActiveRecord::Base
  has_many :photos, dependent: :nullify
  
  has_one :admin_user

  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true

  mount_uploader :logo, LogoUploader
  
  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def access_denied(exception)
    if current_admin_user.admin?
      redirect_to admin_root_path
    else
      redirect_to admin_photos_path
    end
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def photo_download
    if params[:name]
      files = Photo.find(params[:id]).files
      download_file = files.select { |attachment| attachment.path.split("/").last == params[:name] }
      url = download_file.last.file.file
    else
      download_file = Photo.find(params[:id]).files[params[:index].to_i]
      url = download_file.file.file
    end
    send_file url, disposition: 'attachment'
  end
end

app/controllers/photo_albums_controller.rb
class PhotoAlbumsController < ApplicationController
  respond_to :json, :html

  def index
    @photo_albums = PhotoAlbum.includes(:photos).order(start_date: :asc)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photo_album = PhotoAlbum.includes(:photos).find(params[:photo_album_id])
    @current_date = params[:date].present? ? params[:date] : @photo_album.photos.pluck(:date).uniq.first
    if @current_date.present?
      @photos = @photo_album.photos.where(date: @current_date)
    else
      @photos = @photo_album.photos
    end
    @dates = @photo_album.photos.pluck(:date).uniq
  end

  def show
    @photo = Photo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_album_helper.rb
module PhotoAlbumHelper
  def vk_share_link(photo)
    "http://vkontakte.ru/share.php?url=http://z-fest.ru" +
    "&description=Zelenopark" +
    "&image=http://z-fest.ru#{photo.url(:small)}"
  end

  def fb_share_link(photo)
    "https://www.facebook.com/sharer.php?u=http://z-fest.ru"+
    "&t=Zelenopark" +
    "&picture=http://z-fest.ru#{photo.url(:small)}" +
    "&description=Zelenopark"
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/photos/_form.html.slim
.loading
= semantic_form_for [:admin, @photo] do |f|
  = f.inputs 'Общая информация'
    = f.input :photo_album_id, as: :hidden, input_html: { value: current_admin_user.photo_album.id }
    = f.input :date, as: :select, collection: current_admin_user.photo_album.start_date..current_admin_user.photo_album.finish_date
    = f.input :title
    = f.input :description
    - if action_name == 'new'
      = f.input :files, as: :file, input_html: { multiple: true }
    - else
      = f.input :files, as: :file, input_html: { multiple: true }
      = f.inputs 'Фотографии'
        - f.object.files.each_with_index do |file, index|
          p
            = image_tag file.url(:small)
            = link_to "Удалить фото", remove_photo_admin_photo_path(@photo, index: index), data: { confirm: "Вы уверены, что хотите удалить фото?" }

  = f.submit 'Cоздать фотографию', id: 'button'

app/views/layouts/application.html.slim
doctype html
html
  head
    title ng-bind="title" Zelenopark
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .layout
      .layout__wrapper
        = link_to root_path, data: { no_turbolink: true } do
          .layout__aside
            .layout__aside__top
              .logo.logo--small

              .layout__aside__pattern

            .logo.logo--big
              .logo__container

            .promo-text
              .promo-text__header

              .promo-text__body

            .layout__aside__bottom-pattern

        .layout__main
          .layout__main__wrapper
            = yield

app/views/photo_albums/index.html.slim
.cards-list
  - @photo_albums.each do |album|
    .card
      .card__content
        .card__wrapper
          .card__photo
            = link_to image_tag(album.logo.url(:small), alt: ''), photo_album_photos_path(album), data: { no_turbolink: true }

          .card__right
            .card__header
              = link_to album.title, photo_album_photos_path(album), data: { no_turbolink: true }

            .card__description
              = album.description

            .card__footer
              .card__date
                .card__date-icon

                .card__date-text
                  | #{album.start_date.strftime("%d.%m")}-#{album.finish_date.strftime("%d.%m")}

              .card__photo-counter
                .card__photo-icon

                .card__photo-text
                  = album.photos.inject(0){|count, photo| count += photo.files.length}


      - if album.photos.present?
        .card__photos-list
          - album.photos.each do |image|
            - image.files.each do |file|
              .card__photos-list__photo
                = image_tag file.url(:small), alt: ''
          = link_to photo_album_photos_path(album), data: { no_turbolink: true }, class: 'card__photos-list__photo-button' do
            .card__photos-list__photo-icon

            span Посмотреть все фото

app/views/photos/index.html.slim
.galery
  .galery__wrapper
    .galery__navigation
      .galery__navigation__wrapper
        a.galery__navigation__item.galery__navigation__item--left
        - if @photo_album.previous.present?
          = link_to photo_album_photos_path(@photo_album.previous.try(:id)), data: { no_turbolink: true }, class: "galery__navigation__item galery__navigation__item--left"
            .galery__navigation__icon

            .galery__navigation__text Предыдущее событие
        - else
          a.galery__navigation__item.galery__navigation__item--left.inactive
            .galery__navigation__icon.galery__navigation__icon--arrow-left-gray

            .galery__navigation__text Предыдущее событие

        = link_to root_path, data: { no_turbolink: true }, class: "galery__navigation__item galery__navigation__item--all"

          .galery__navigation__icon

          .galery__navigation__text Вернуться на главную

        - if @photo_album.next.present?
          = link_to photo_album_photos_path(@photo_album.next.try(:id)), data: { no_turbolink: true }, class: "galery__navigation__item galery__navigation__item--right"
            .galery__navigation__text Следующее событие
            .galery__navigation__icon
        - else
          a.galery__navigation__item.galery__navigation__item--right.inactive
            .galery__navigation__text Следующее событие
            .galery__navigation__icon.galery__navigation__icon--arrow-right-gray

      .card.card--no-top-shadow
        .card__content
          .card__wrapper
            .card__photo
              = image_tag @photo_album.logo.url(:small), lazy: true, alt: ''
            .card__right
              .card__header
                = @photo_album.title
              .card__description
                = @photo_album.description
              .card__footer
                .card__date
                  .card__date-icon

                  .card__date-text
                    = @photo_album.start_date.strftime("%d-%m-%Y")
                .card__photo-counter
                  .card__photo-icon

                  .card__photo-text
                    = @photo_album.photos.inject(0){|count, photo| count += photo.files.length}

    .galery__photos
      .galery__photos__navigation
        - @dates.each do |date|
          div class="#{@current_date.to_date == date ? 'galery__photos__navigation-button galery__photos__navigation-button--active' : 'galery__photos__navigation-button'}"
            = link_to photos_filter_path(@photo_album,date), data: { no_turbolink: true }
              b = date.strftime("%d-%m-%Y")
      ul.galery__preview-list#grid.effect-4.grid
        - index = -1
        - @photos.each do |photo|
          - photo.files.each_with_index do |file, json_index|
            li.galery__preview-item style="width: 20%"
              .galery__preview-photo
                .galery__preview-photo__actions
                  .galery__preview-photo__actions-wrapper
                    .galery__preview-photo__action-slider data-index="#{index+=1}"
                      .galery__preview-photo__action-slider__icon

                      .galery__preview-photo__action-slider__text
                        | Подробнее

                    .galery__preview-photo__action-shares
                      = link_to vk_share_link(file), target: "_blank", onclick: "return Share.me(this);" do
                        .galery__preview-photo__action-share.galery__preview-photo__action-share--vk
                      = link_to fb_share_link(file), target: "_blank", onclick: "return Share.me(this);" do
                        .galery__preview-photo__action-share.galery__preview-photo__action-share--facebook

                      = link_to downloads_photo_download_path(id: photo.id, index: json_index), data: { no_turbolink: true } do
                        .galery__preview-photo__action-share.galery__preview-photo__action-share--download
                .galery__preview-photo__image
                  = image_tag file.url(:small), alt: ''
              - if photo.files.length == 1
                - if photo.title.present?
                  .galery__preview-header
                    = photo.title
                - if photo.description.present?
                  .galery__preview-description
                    = photo.description
.modalwin
  .modalwin__wrapper
    .modalwin__background

    .modalwin__body
      .modalwin__logo
      .nodalwin__closer &times

      .modalwin__body__nav-button.modalwin__body__nav-button--prev data-direction="<"

      .modalwin__body__nav-button.modalwin__body__nav-button--next data-direction=">"
      .modalwin__slider.fotorama data-width="680" data-height="440" data-margin="25" data-nav="thumbs" data-arrows="always" data-thumbheight="80" data-thumbwidth="80" data-fit="contain"
        - @photos.each do |photo|
          - photo.files.each do |file|
            a href="#{file.url(:medium)}"

      .modalwin__slider-aside
        .modalwin__slider-aside__wrapper
          .modalwin__slider-aside__content
            .modalwin__slider-aside__header

            .modalwin__slider-aside__description Повседневная практика показывает Повседневная практика показывает Повседневная практика показывает Повседневная практика показывает Повседневная практика показывает

          .modalwin__slider-aside__controls

            a href="#" onclick="return Share.vkontakte('http://z-fest.ru', 'Zelenopark', 'Zelenopark');"
              .modalwin__slider-aside__control.modalwin__slider-aside__control--vk Опубликовать вконтакте
            br
            a href="#" onclick="return Share.facebook('http://z-fest.ru', 'Zelenopark', 'Zelenopark');"
              .modalwin__slider-aside__control.modalwin__slider-aside__control--facebook Опубликовать в facebook
            br
            a href="#" id='download-link' download='' onclick='return Share.downloadImage(this);' data-no-turbolink='true'
              .modalwin__slider-aside__control.modalwin__slider-aside__control--download Скачать фотографию